// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVilnKE11SphnnujGSE6mmFWNFJ9K1xM',
    appId: '1:405196330001:web:af55b9311908c0dfd64db0',
    messagingSenderId: '405196330001',
    projectId: 'final-wecode-project',
    authDomain: 'final-wecode-project.firebaseapp.com',
    storageBucket: 'final-wecode-project.appspot.com',
    measurementId: 'G-WY27R23MRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-H7Iw5wRsc8uqqoDlE-Hq6sP0XG5fU4',
    appId: '1:405196330001:android:a4c9113275ff065cd64db0',
    messagingSenderId: '405196330001',
    projectId: 'final-wecode-project',
    storageBucket: 'final-wecode-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJE7G3NXK9-95rUHIiDzoi3UM7BmOFaHY',
    appId: '1:405196330001:ios:fd9a9942e4c4bab1d64db0',
    messagingSenderId: '405196330001',
    projectId: 'final-wecode-project',
    storageBucket: 'final-wecode-project.appspot.com',
    iosClientId: '405196330001-fs8ijvp5pnd9h3khuogfvenqn54m0j16.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycodeWecodeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJE7G3NXK9-95rUHIiDzoi3UM7BmOFaHY',
    appId: '1:405196330001:ios:fd9a9942e4c4bab1d64db0',
    messagingSenderId: '405196330001',
    projectId: 'final-wecode-project',
    storageBucket: 'final-wecode-project.appspot.com',
    iosClientId: '405196330001-fs8ijvp5pnd9h3khuogfvenqn54m0j16.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycodeWecodeProject',
  );
}
